### ISSUE TITLE
(vcom 66): Execution of vlib.exe failed

### ISSUE THREAD

**Issue by guilbaudl** [fransschreuder/8b10b_VHDL#1]
I don't know if this is only from my setup, but this is necessary to type
`vlib work`
before the command
`do simulate-modelsim.tcl`
I am using Modelsim 18.1 and now, the tests run perfectly

**Comment by fransschreuder** [comment]
Hello, could you check the branch https://github.com/fransschreuder/8b10b_VHDL/tree/issue-1_add_vlib_work?
Thanks for reporting

**Comment by guilbaudl** [comment]
Hello,

Yes, it works properly! Also, it was not possible for me to run the command 
do ./compile_all.do -c
but I think it is surely due to my environment. I have to run this command without -c or I get this error: "Error: couldn't open "-c/component_list.txt": no such file or directory"

If you want, I replace the process named "alt7_proc" in the encoder by a conditional statement and from what I understood from the tests, it works properly. Here is the modification I have done:

CURRENT CHANGE
=======================
alt7_proc: process(fi, gi, hi, KI, ei, dispin, di, l31, l13)
        variable dispval : std_logic;
    begin
        if dispin = '1' then
            dispval := (not ei and di and l31);
        else
            dispval := (ei and not di and l13);
        end if;
        alt7 <= fi and gi and hi and (KI or dispval);
    end process;
========================
becomes

INCOMING CHANGE
=======================
alt7  <= (fi and gi and hi and (ki or (not ei and di and l31))) when dispin = '1' else (fi and gi and hi and (ki or (ei and not di and l13)));
=======================

My pleasure, thank you for coding this 8b10b block!

Regards


----- Mail original -----
De: "Frans Schreuder" ***@***.***>
À: "fransschreuder/8b10b_VHDL" ***@***.***>
Cc: "Loan GUILBAUD" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 12 Avril 2021 14:44:28
Objet: Re: [fransschreuder/8b10b_VHDL] (vcom 66): Execution of vlib.exe failed (#1)

Hello, could you check the branch https://github.com/fransschreuder/8b10b_VHDL/tree/issue-1_add_vlib_work?
Thanks for reporting

**Comment by fransschreuder** [comment]
I don't think that changes anything functional, does it? I think the process is slightly more readable, but it's a matter of taste.

**Comment by guilbaudl** [comment]
I don't know, because the difference would be in the implementation and I haven't tried both revisions. But the risk with the process and the variable could be that more than only logical gates would be instantiated, even if the process is combinatorial. It is only visible with implementation, it could be interesting to see the difference between these 2 codes!

Regards

----- Mail original -----
De: "Frans Schreuder" ***@***.***>
À: "fransschreuder/8b10b_VHDL" ***@***.***>
Cc: "Loan GUILBAUD" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 12 Avril 2021 16:50:59
Objet: Re: [fransschreuder/8b10b_VHDL] (vcom 66): Execution of vlib.exe failed (#1)

I don't think that changes anything functional, does it? I think the process is slightly more readable, but it's a matter of taste.
